baseurl = "https://www.browillow.com"
title = "BroWillow"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Copyright 2018: Jordan Lee Osier"
googleAnalytics = "UA-128351354-1" # delete or comment to disable Google Analytics JS generation
#disqusShortname = "YourDisqusShortname" #delete or comment to disable Disqus comments

[author]
  name = "Jordan L. Osier"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Honest Discussions on Theology, Philosophy, Science, and Politics"
  Author = "Jordan Osier"
  postSummariesFrontPage = 6 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = true #set to false to exclude read time from header of post
  # This will load all the CSS defined in the list
  customCSS = ["/css/site.css"]
  
[[params.social]]
  title = "twitter"
  url = "https://twitter.com/BroWillow"
[[params.social]]
  title = "youtube"
  url = "https://www.youtube.com/channel/UCfWmwxEIMU018Dzj52HghfQ"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/BroWillow"
[[params.social]]
  title = "instagram"
  url = "https://www.instagram.com/BroWillow"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
